In [1]:
import torch
import torchvision

# Process the trained weights from Training stage 1

In [3]:
# model path (get from training stage 1)
path = "../model-9804.pth"
m1 = torch.load(path, map_location=torch.device('cpu') )

In [4]:
for i in m1.keys():
    print(i)

model


In [5]:
for i in m1["model"].keys():
    print(i)

base_network.conv1.weight
base_network.bn1.weight
base_network.bn1.bias
base_network.bn1.running_mean
base_network.bn1.running_var
base_network.bn1.num_batches_tracked
base_network.layer1.0.conv1.weight
base_network.layer1.0.bn1.weight
base_network.layer1.0.bn1.bias
base_network.layer1.0.bn1.running_mean
base_network.layer1.0.bn1.running_var
base_network.layer1.0.bn1.num_batches_tracked
base_network.layer1.0.conv2.weight
base_network.layer1.0.bn2.weight
base_network.layer1.0.bn2.bias
base_network.layer1.0.bn2.running_mean
base_network.layer1.0.bn2.running_var
base_network.layer1.0.bn2.num_batches_tracked
base_network.layer1.0.conv3.weight
base_network.layer1.0.bn3.weight
base_network.layer1.0.bn3.bias
base_network.layer1.0.bn3.running_mean
base_network.layer1.0.bn3.running_var
base_network.layer1.0.bn3.num_batches_tracked
base_network.layer1.0.downsample.0.weight
base_network.layer1.0.downsample.1.weight
base_network.layer1.0.downsample.1.bias
base_network.layer1.0.downsample.1.running

In [6]:
# rename, so the weights get from training stage 1 can be used for training stage 2
for i in list(m1["model"].keys()):
    if i.startswith("base_network."):
        new_key = i.split("base_network.")[1]
        m1["model"][new_key] = m1["model"][i]
        del m1["model"][i]
        
for i in m1["model"].keys():
    print(i)

classifier_layer.weight
classifier_layer.bias
conv1.weight
bn1.weight
bn1.bias
bn1.running_mean
bn1.running_var
bn1.num_batches_tracked
layer1.0.conv1.weight
layer1.0.bn1.weight
layer1.0.bn1.bias
layer1.0.bn1.running_mean
layer1.0.bn1.running_var
layer1.0.bn1.num_batches_tracked
layer1.0.conv2.weight
layer1.0.bn2.weight
layer1.0.bn2.bias
layer1.0.bn2.running_mean
layer1.0.bn2.running_var
layer1.0.bn2.num_batches_tracked
layer1.0.conv3.weight
layer1.0.bn3.weight
layer1.0.bn3.bias
layer1.0.bn3.running_mean
layer1.0.bn3.running_var
layer1.0.bn3.num_batches_tracked
layer1.0.downsample.0.weight
layer1.0.downsample.1.weight
layer1.0.downsample.1.bias
layer1.0.downsample.1.running_mean
layer1.0.downsample.1.running_var
layer1.0.downsample.1.num_batches_tracked
layer1.1.conv1.weight
layer1.1.bn1.weight
layer1.1.bn1.bias
layer1.1.bn1.running_mean
layer1.1.bn1.running_var
layer1.1.bn1.num_batches_tracked
layer1.1.conv2.weight
layer1.1.bn2.weight
layer1.1.bn2.bias
layer1.1.bn2.running_mean
layer1

In [7]:
torch.save(m1["model"], "../P2K-nobottle-Ktarget-9804-supervised.pth")

In [8]:
# remove num_batches_tracked
for i in list(m1["model"].keys()):
    if i.endswith("num_batches_tracked"):
        del m1["model"][i]
        
for i in m1["model"].keys():
    print(i)

classifier_layer.weight
classifier_layer.bias
conv1.weight
bn1.weight
bn1.bias
bn1.running_mean
bn1.running_var
layer1.0.conv1.weight
layer1.0.bn1.weight
layer1.0.bn1.bias
layer1.0.bn1.running_mean
layer1.0.bn1.running_var
layer1.0.conv2.weight
layer1.0.bn2.weight
layer1.0.bn2.bias
layer1.0.bn2.running_mean
layer1.0.bn2.running_var
layer1.0.conv3.weight
layer1.0.bn3.weight
layer1.0.bn3.bias
layer1.0.bn3.running_mean
layer1.0.bn3.running_var
layer1.0.downsample.0.weight
layer1.0.downsample.1.weight
layer1.0.downsample.1.bias
layer1.0.downsample.1.running_mean
layer1.0.downsample.1.running_var
layer1.1.conv1.weight
layer1.1.bn1.weight
layer1.1.bn1.bias
layer1.1.bn1.running_mean
layer1.1.bn1.running_var
layer1.1.conv2.weight
layer1.1.bn2.weight
layer1.1.bn2.bias
layer1.1.bn2.running_mean
layer1.1.bn2.running_var
layer1.1.conv3.weight
layer1.1.bn3.weight
layer1.1.bn3.bias
layer1.1.bn3.running_mean
layer1.1.bn3.running_var
layer1.2.conv1.weight
layer1.2.bn1.weight
layer1.2.bn1.bias
layer1.2

In [9]:
torch.save(m1["model"], "../P2K-nobottle-Ktarget-9804-supervised-Notrack.pth")

# Compare two faster rcnn pretrained weight

In [42]:
resnet_50_path = "../resnet50.pth"
resnet_50 = torch.load(resnet_50_path, map_location=torch.device('cpu'))
for i in resnet_50.keys():
    print(i)

conv1.weight
bn1.running_mean
bn1.running_var
bn1.weight
bn1.bias
layer1.0.conv1.weight
layer1.0.bn1.running_mean
layer1.0.bn1.running_var
layer1.0.bn1.weight
layer1.0.bn1.bias
layer1.0.conv2.weight
layer1.0.bn2.running_mean
layer1.0.bn2.running_var
layer1.0.bn2.weight
layer1.0.bn2.bias
layer1.0.conv3.weight
layer1.0.bn3.running_mean
layer1.0.bn3.running_var
layer1.0.bn3.weight
layer1.0.bn3.bias
layer1.0.downsample.0.weight
layer1.0.downsample.1.running_mean
layer1.0.downsample.1.running_var
layer1.0.downsample.1.weight
layer1.0.downsample.1.bias
layer1.1.conv1.weight
layer1.1.bn1.running_mean
layer1.1.bn1.running_var
layer1.1.bn1.weight
layer1.1.bn1.bias
layer1.1.conv2.weight
layer1.1.bn2.running_mean
layer1.1.bn2.running_var
layer1.1.bn2.weight
layer1.1.bn2.bias
layer1.1.conv3.weight
layer1.1.bn3.running_mean
layer1.1.bn3.running_var
layer1.1.bn3.weight
layer1.1.bn3.bias
layer1.2.conv1.weight
layer1.2.bn1.running_mean
layer1.2.bn1.running_var
layer1.2.bn1.weight
layer1.2.bn1.bias
lay

In [41]:
fasterrcnn_resnet50_fpn_coco_path = "../fasterrcnn_resnet50_fpn_coco.pth"
fasterrcnn_resnet50_fpn_coco = torch.load(fasterrcnn_resnet50_fpn_coco_path, map_location=torch.device('cpu'))
for i in fasterrcnn_resnet50_fpn_coco.keys():
    print(i)

backbone.body.conv1.weight
backbone.body.bn1.weight
backbone.body.bn1.bias
backbone.body.bn1.running_mean
backbone.body.bn1.running_var
backbone.body.layer1.0.conv1.weight
backbone.body.layer1.0.bn1.weight
backbone.body.layer1.0.bn1.bias
backbone.body.layer1.0.bn1.running_mean
backbone.body.layer1.0.bn1.running_var
backbone.body.layer1.0.conv2.weight
backbone.body.layer1.0.bn2.weight
backbone.body.layer1.0.bn2.bias
backbone.body.layer1.0.bn2.running_mean
backbone.body.layer1.0.bn2.running_var
backbone.body.layer1.0.conv3.weight
backbone.body.layer1.0.bn3.weight
backbone.body.layer1.0.bn3.bias
backbone.body.layer1.0.bn3.running_mean
backbone.body.layer1.0.bn3.running_var
backbone.body.layer1.0.downsample.0.weight
backbone.body.layer1.0.downsample.1.weight
backbone.body.layer1.0.downsample.1.bias
backbone.body.layer1.0.downsample.1.running_mean
backbone.body.layer1.0.downsample.1.running_var
backbone.body.layer1.1.conv1.weight
backbone.body.layer1.1.bn1.weight
backbone.body.layer1.1.bn1.

In [83]:
# compare two faster rcnn pretrained weight

for i in resnet_50.keys():
    print(i)
    key_in_faster_rcnn = "backbone.body." + i
    if key_in_faster_rcnn in FBN_only_trained_2_layers["model"].keys(): # fasterrcnn_resnet50_fpn_coco
        print(resnet_50[i] == FBN_only_trained_2_layers["model"][key_in_faster_rcnn])


conv1.weight
tensor([[[[True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          ...,
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True]],

         [[True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          ...,
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True]],

         [[True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          ...,
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, Tru

tensor([[[[True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, True, True],
          [True, True, True]],

         ...,

         [[True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, True, True],
          [True, True, True]]],


        [[[True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, True, True],
          [True, True, True]],

         ...,

         [[True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, T

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, Tr

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, Tr

tensor([[[[False, False, False],
          [False, False, False],
          [False, False, False]],

         [[False, False, False],
          [False, False, False],
          [False, False, False]],

         [[False, False, False],
          [False, False, False],
          [False, False, False]],

         ...,

         [[False, False, False],
          [False, False, False],
          [False, False, False]],

         [[False, False, False],
          [False, False, False],
          [False, False, False]],

         [[False, False, False],
          [False, False, False],
          [False, False, False]]],


        [[[False, False, False],
          [False, False, False],
          [False, False, False]],

         [[False, False, False],
          [False, False, False],
          [False, False, False]],

         [[False, False, False],
          [False, False, False],
          [False, False, False]],

         ...,

         [[False, False, False],
          [False, False, F

tensor([[[[False]],

         [[False]],

         [[False]],

         ...,

         [[False]],

         [[False]],

         [[False]]],


        [[[False]],

         [[False]],

         [[False]],

         ...,

         [[False]],

         [[False]],

         [[False]]],


        [[[False]],

         [[False]],

         [[False]],

         ...,

         [[False]],

         [[False]],

         [[False]]],


        ...,


        [[[False]],

         [[False]],

         [[False]],

         ...,

         [[False]],

         [[False]],

         [[False]]],


        [[[False]],

         [[False]],

         [[False]],

         ...,

         [[False]],

         [[False]],

         [[False]]],


        [[[False]],

         [[False]],

         [[False]],

         ...,

         [[False]],

         [[False]],

         [[False]]]])
layer4.0.bn3.running_mean
tensor([True, True, True,  ..., True, True, True])
layer4.0.bn3.running_var
tensor([True, True, True, 

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, Tr

In [72]:
print(resnet_50["fc.weight"].shape) 
print(fasterrcnn_resnet50_fpn_coco["roi_heads.box_predictor.cls_score.weight"].shape)

torch.Size([1000, 2048])
torch.Size([91, 1024])
